#!/bin/bash
set -x
BASE=$(realpath $(dirname $0))
CMBASE=$(realpath $ANDROID_PRODUCT_OUT/../../../../)

sudo mount -t overlay overlay -o ro -olowerdir=\
$CMBASE/frameworks/base/core/java:\
$CMBASE/frameworks/base/services/core/java:\
$CMBASE/frameworks/base/telephony/java:\
$CMBASE/frameworks/base/telecomm/java:\
$CMBASE/frameworks/opt/telephony/src/java:\
$CMBASE/libcore/luni/src/main/java:\
$CMBASE/libcore/dalvik/src/main/java:\
$CMBASE/packages/services/Telephony/src:\
$CMBASE/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/src/core/java\
 \
$BASE/lib/java/android/
